# Generated by Django 4.1.7 on 2023-03-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0003_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
