# Generated by Django 4.1.7 on 2023-03-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0004_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['position', 'pk']},
        ),
    ]
