# Generated by Django 4.1.7 on 2023-04-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
