# Generated by Django 4.1.7 on 2023-04-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0008_player_is_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hand',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TurnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('hand', models.IntegerField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texas_api.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texas_api.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texas_api.player')),
            ],
        ),
    ]
