# Generated by Django 4.1.7 on 2023-04-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0009_game_hand_turnhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='waiting_for_continue',
            field=models.BooleanField(default=False),
        ),
    ]
