# Generated by Django 4.1.7 on 2023-04-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0010_player_waiting_for_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tricks',
            field=models.IntegerField(default=0),
        ),
    ]
