# Generated by Django 4.1.7 on 2023-04-17 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texas_api', '0012_game_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
