# Generated by Django 4.1.7 on 2023-04-20 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texas_api', '0013_game_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='loser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='end_game',
            field=models.BooleanField(default=False),
        ),
    ]
