# Generated by Django 4.1.7 on 2023-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0014_game_losers_turnhistory_end_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_betting_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='pot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
