# Generated by Django 4.1.7 on 2023-05-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0017_player_fold'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BetTurnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_turn', models.IntegerField()),
                ('hand', models.IntegerField()),
                ('bet_action', models.CharField(choices=[('CHECK', 'check'), ('OPEN', 'open'), ('FOLD', 'fold'), ('CALL', 'call'), ('RAISE', 'raise')], max_length=5, null=True)),
                ('bet_amount', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texas_api.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texas_api.player')),
            ],
        ),
    ]
