# Generated by Django 4.1.7 on 2023-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0018_game_bet_turn_betturnhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='betturnhistory',
            name='player_money',
            field=models.IntegerField(default=0),
        ),
    ]
