# Generated by Django 5.0.1 on 2024-01-30 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0020_player_background_color_player_hat_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_timer_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
