# Generated by Django 5.0.1 on 2024-02-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0021_game_last_timer_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choose_turn',
            field=models.BooleanField(default=False),
        ),
    ]
