# Generated by Django 5.0.1 on 2024-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0022_player_choose_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
