# Generated by Django 5.0.1 on 2024-02-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0023_game_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
