# Generated by Django 5.0.1 on 2024-03-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0024_game_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bet_turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='betting',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_betting_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fold',
        ),
        migrations.DeleteModel(
            name='BetTurnHistory',
        ),
    ]
