# Generated by Django 5.0.1 on 2024-03-24 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0025_remove_game_bet_turn_remove_game_betting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_gift',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
