# Generated by Django 5.0.1 on 2024-03-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_api', '0026_player_last_gift_alter_player_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='buy_in',
            field=models.IntegerField(default=0),
        ),
    ]
